name: "server deploy debian (child)"

on:
  # Triggered from other workflows.
  workflow_call:
    inputs:
      jobDistros:
        description: "jobDistros: List of Ubuntu codenames to build for"
        required: true
        # There is no `list` type, so use a raw JSON array and `fromJSON()`.
        # Example: '["xenial", "bionic", "focal"]'
        type: "string"
        default: '["noble"]'
      jobRelease:
        description: "jobRelease: Enable to build release versions; disable for development builds"
        required: false
        type: "boolean"
        default: false
      jobDeployName:
        description: "jobDeployName: Custom name given to the deployment"
        required: false
        type: "string"
        default: ""
      runnerGroup:
        description: "runnerGroup: Set of runners where the workflow jobs should be run"
        required: false
        type: "string"
        default: ""

    secrets:
      APTLY_SSH_PRIVATE_KEY:
        description: "SSH private key for Aptly proxy server"
        required: true

defaults:
  run:
    shell: "bash --noprofile --norc -o errexit -o errtrace -o pipefail -o nounset -o xtrace {0}"

jobs:
  build:
    runs-on: ["self-hosted", "${{ inputs.runnerGroup }}"]
    strategy:
      # Run each configuration sequentially.
      # Aptly has a global lock and doesn't support concurrent operations from multiple jobs.
      max-parallel: 1
      matrix:
        jobDistro: ${{ fromJSON(inputs.jobDistros) }}
    timeout-minutes: 30
    steps:
      # Action: https://github.com/actions/checkout
      - name: "Checkout"
        uses: "actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11" # v4.1.1

      - name: "Configure the environment for ci-scripts/"
        working-directory: "ci-scripts/"
        run: |
          echo "$PWD" >>$GITHUB_PATH
          echo "KURENTO_SCRIPTS_HOME=$PWD" >>$GITHUB_ENV
          echo "JOB_TIMESTAMP=$(date --utc +%Y%m%d%H%M%S)" >>$GITHUB_ENV

      # Action: https://github.com/actions/download-artifact
      - name: "Copy artifacts from previous jobs"
        id: "copy-artifacts"
        uses: "actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a" # v3.0.2
        with:
          name: "artifacts"
          path: "artifacts/"

      - name: "Configure the environment for job script"
        run: |
          # Path to the SSH key used by `ci_job_deploy_debian.sh`.
          # Note: No need to clean, $RUNNER_TEMP/ is deleted after each run.
          APTLY_SSH_KEY_PATH="$RUNNER_TEMP/id_aptly_ssh"
          echo "APTLY_SSH_KEY_PATH=$APTLY_SSH_KEY_PATH" >>$GITHUB_ENV
          echo "${{ secrets.APTLY_SSH_PRIVATE_KEY }}" >"$APTLY_SSH_KEY_PATH"
          chmod 0400 "$APTLY_SSH_KEY_PATH"

      - name: "Run job script"
        env:
          JOB_DISTRO: "${{ matrix.jobDistro }}"
          JOB_RELEASE: "${{ inputs.jobRelease }}"
          JOB_DEPLOY_NAME: "${{ inputs.jobDeployName }}"
          APTLY_GPG_SUBKEY: "${{ vars.APTLY_GPG_SUBKEY }}"
        working-directory: "artifacts/"
        run: "ci_job_deploy_debian.sh"
